### ISSUE TITLE
Addon version 4.4.2 doesn't work with blender 4.5.3

### ISSUE THREAD

**Issue by AnthonyAttwood** [xavier150/Blender-For-UnrealEngine-Addons#234]
Hi there, the addon will no activate for Blender version 4.5.3. The error message I get is 

"module 'bl_ext.user_default.unrealengine_assets_exporter' has no attribute 'register'"

This is when I'm trying to check the box in the Add-Ons tab of Preferences, it's greyed out and once clicking the checkbox this error occurs.

**Comment by xavier150** [comment]
Hello, it look like the addon installation failed, you cna try this steps ?
- Uninstall
- Restart Blender
- Install
- Restart Blender

It works?

**Comment by AnthonyAttwood** [comment]
> Hello, it look like the addon installation failed, you cna try this steps ?
> 
> * Uninstall
> * Restart Blender
> * Install
> * Restart Blender
> 
> It works?

Hi there, unfortunately it didn't work. Upon trying to install again after restarting blender I get the same error " module 'bl_ext.user_default.unrealengine_assets_exporter' has no attribute 'register' "

**Comment by xavier150** [comment]
Ok, in Blender just after install you can do `Windows ->Toggle System Console` And can copy paste the logs?
Also how you get the Addon .zip?

**Comment by AnthonyAttwood** [comment]
> Ok, in Blender just after install you can do `Windows ->Toggle System Console` And can copy paste the logs? Also how you get the Addon .zip?

Hi, I have successfully installed the addon now. As it turns out, I didn't know there was a zip version for each blender version. My mistake, sorry. I installed the version for 4.5 and it worked just fine. Thanks for you help.

**Comment by xavier150** [comment]
Oh I see, happy that all working good now!
I will close this issue
