### ISSUE TITLE
Error while importing into UE 5.3

### ISSUE THREAD

**Issue by ARevontulet** [xavier150/Blender-For-UnrealEngine-Addons#177]
Hello! I'm trying to import camera motion from Blender 3.6 into UE5.3 (following this tutorial https://www.youtube.com/watch?v=Ta0am2wC-SI) using addon version [Rev 0.4.1]. But after pasting the script I get a bunch of error messages and the created sequence ends up empty. Not sure if I'm doing something wrong or if the script doesn't work properly in the newer version.
Could you look into it? Thanks!

LogPython: Warning: F:/test/ExportedFbx/ImportSequencerScript.py:122: DeprecationWarning: LevelSequence: Function 'add_master_track' on 'MovieSceneSequenceExtensions' is deprecated: AddMasterTrack is deprecated. Please use AddTrack instead
  camera_cut_track = seq.add_master_track(unreal.MovieSceneCameraCutTrack)
LogPython: Start camera import 1/1 :Camera
LogEditor: Attempting to add actor of class 'CineCameraActor' to level at 0.00,0.00,0.00
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "F:/test/ExportedFbx/ImportSequencerScript.py", line 294, in <module>
LogPython: Error:     print(CreateSequencer())
LogPython: Error:   File "F:/test/ExportedFbx/ImportSequencerScript.py", line 148, in CreateSequencer
LogPython: Error:     AddSequencerSectionFloatKeysByIniFile(sectionFocalLength, camera_tracks['Camera FocalLength'])
LogPython: Error:   File "F:/test/ExportedFbx/ImportSequencerScript.py", line 93, in AddSequencerSectionFloatKeysByIniFile
LogPython: Error:     sequencer_section.get_channels()[0].add_key(frame, value)
LogPython: Error: AttributeError: 'MovieSceneFloatSection' object has no attribute 'get_channels'

UPD 2: Works in UE 5.0.3, but I unfortunately already have a project setup all for UE 5.3😅

**Comment by xavier150** [comment]
Thanks for the report! I will check that soon

**Comment by xx88xx** [comment]
also having this issue. looks like the unreal APIs might have changed in 5.3?

**Comment by xavier150** [comment]
Hello @ARevontulet and @xx88xx 
Sorry for the delay.

I update Unreal Engine deprecated functions in the sequencer import and fixed this issue!
Dev Branch -> https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-dev-branch

I will close this issue when I release update v0.4.2

**Comment by ARevontulet** [comment]
> Hello @ARevontulet and @xx88xx Sorry for the delay.
> 
> I update Unreal Engine deprecated functions in the sequencer import and fixed this issue! Dev Branch -> https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-dev-branch
> 
> I will close this issue when I release update v0.4.2

Great! Thanks!

**Comment by xavier150** [comment]
I release v0.4.2 Preview 1 so I close this issue ^^
https://github.com/xavier150/Blender-For-UnrealEngine-Addons/wiki/Download-And-Installation
